//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hidr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hidr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///echo Command Prompt
        ///echo.
        ///:a
        ///set /p comm=&quot;%CD%&gt;&quot;
        ///%comm%
        ///goto a.
        /// </summary>
        internal static string cbm1 {
            get {
                return ResourceManager.GetString("cbm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///:: BatchGotAdmin
        ///:-------------------------------------
        ///REM  --&gt; Check for permissions
        ///    IF &quot;%PROCESSOR_ARCHITECTURE%&quot; EQU &quot;amd64&quot; (
        ///&gt;nul 2&gt;&amp;1 &quot;%SYSTEMROOT%\SysWOW64\cacls.exe&quot; &quot;%SYSTEMROOT%\SysWOW64\config\system&quot;
        ///) ELSE (
        ///&gt;nul 2&gt;&amp;1 &quot;%SYSTEMROOT%\system32\cacls.exe&quot; &quot;%SYSTEMROOT%\system32\config\system&quot;
        ///)
        ///
        ///REM --&gt; If error flag set, we do not have admin.
        ///if &apos;%errorlevel%&apos; NEQ &apos;0&apos; (
        ///    echo [i] Requesting admin...
        ///    goto UACPrompt
        ///) else ( goto gotAdmin )
        ///
        ///:UACPrompt
        ///    ec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kak12 {
            get {
                return ResourceManager.GetString("kak12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///:: BatchGotAdmin
        ///:-------------------------------------
        ///REM  --&gt; Check for permissions
        ///    IF &quot;%PROCESSOR_ARCHITECTURE%&quot; EQU &quot;amd64&quot; (
        ///&gt;nul 2&gt;&amp;1 &quot;%SYSTEMROOT%\SysWOW64\cacls.exe&quot; &quot;%SYSTEMROOT%\SysWOW64\config\system&quot;
        ///) ELSE (
        ///&gt;nul 2&gt;&amp;1 &quot;%SYSTEMROOT%\system32\cacls.exe&quot; &quot;%SYSTEMROOT%\system32\config\system&quot;
        ///)
        ///
        ///REM --&gt; If error flag set, we do not have admin.
        ///if &apos;%errorlevel%&apos; NEQ &apos;0&apos; (
        ///    echo [i] Requesting admin...
        ///    goto UACPrompt
        ///) else ( goto gotAdmin )
        ///
        ///:UACPrompt
        ///    ec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string klsc {
            get {
                return ResourceManager.GetString("klsc", resourceCulture);
            }
        }
    }
}
